"""initial schema

Revision ID: 8ac05542b36d
Revises: 
Create Date: 2026-09-02 21:23:07.979090

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import paperwrench.db.base


revision: str = '8ac05542b36d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('filterset_json', sa.Text(), nullable=True),
    sa.Column('created_at', paperwrench.db.base.UtcDateTime(), nullable=False),
    sa.Column('updated_at', paperwrench.db.base.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections')),
    sa.UniqueConstraint('name', name=op.f('uq_collections_name'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('filterset_json', sa.Text(), nullable=True),
    sa.Column('transformation_json', sa.Text(), nullable=True),
    sa.Column('document_ids_json', sa.Text(), nullable=False),
    sa.Column('rollback_of_job_id', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('succeeded_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('paperless_api_version', sa.Integer(), nullable=True),
    sa.Column('paperless_server_version', sa.String(length=32), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', paperwrench.db.base.UtcDateTime(), nullable=False),
    sa.Column('started_at', paperwrench.db.base.UtcDateTime(), nullable=True),
    sa.Column('finished_at', paperwrench.db.base.UtcDateTime(), nullable=True),
    sa.Column('heartbeat_at', paperwrench.db.base.UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rollback_of_job_id'], ['jobs.id'], name=op.f('fk_jobs_rollback_of_job_id_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_jobs_status', ['status'], unique=False)

    op.create_table('runtime_lock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.String(length=64), nullable=False),
    sa.Column('acquired_at', paperwrench.db.base.UtcDateTime(), nullable=False),
    sa.Column('heartbeat_at', paperwrench.db.base.UtcDateTime(), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_runtime_lock_singleton')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runtime_lock'))
    )
    op.create_table('schemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('applies_when_json', sa.Text(), nullable=False),
    sa.Column('rules_json', sa.Text(), nullable=False),
    sa.Column('created_at', paperwrench.db.base.UtcDateTime(), nullable=False),
    sa.Column('updated_at', paperwrench.db.base.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schemas')),
    sa.UniqueConstraint('name', name=op.f('uq_schemas_name'))
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_page_size', sa.Integer(), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('updated_at', paperwrench.db.base.UtcDateTime(), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_settings_singleton')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings'))
    )
    op.create_table('collection_documents',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('added_at', paperwrench.db.base.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_collection_documents_collection_id_collections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'document_id', name=op.f('pk_collection_documents'))
    )
    op.create_table('job_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('document_title', sa.Text(), nullable=True),
    sa.Column('field_kind', sa.String(length=32), nullable=False),
    sa.Column('field_key', sa.String(length=255), nullable=False),
    sa.Column('before_value_json', sa.Text(), nullable=True),
    sa.Column('intended_value_json', sa.Text(), nullable=True),
    sa.Column('written_value_json', sa.Text(), nullable=True),
    sa.Column('before_custom_fields_json', sa.Text(), nullable=True),
    sa.Column('source_modified', paperwrench.db.base.UtcDateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('rollback_of_operation_id', sa.Integer(), nullable=True),
    sa.Column('started_at', paperwrench.db.base.UtcDateTime(), nullable=True),
    sa.Column('finished_at', paperwrench.db.base.UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_operations_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rollback_of_operation_id'], ['job_operations.id'], name=op.f('fk_job_operations_rollback_of_operation_id_job_operations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_operations')),
    sa.UniqueConstraint('job_id', 'document_id', 'field_kind', 'field_key', name='ops_job_doc_field')
    )
    with op.batch_alter_table('job_operations', schema=None) as batch_op:
        batch_op.create_index('ix_ops_doc', ['document_id'], unique=False)
        batch_op.create_index('ix_ops_job', ['job_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_operations', schema=None) as batch_op:
        batch_op.drop_index('ix_ops_job')
        batch_op.drop_index('ix_ops_doc')

    op.drop_table('job_operations')
    op.drop_table('collection_documents')
    op.drop_table('settings')
    op.drop_table('schemas')
    op.drop_table('runtime_lock')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status')
        batch_op.drop_index('ix_jobs_created_at')

    op.drop_table('jobs')
    op.drop_table('collections')
    # ### end Alembic commands ###
